import Header from "@/components/Header";
import "./globals.css";
import { Jost } from "next/font/google";

export const metadata = {
  title: "Designo",
  description: "Generated by create next app",
};

const jost = Jost({
  variable: "--font-jost",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jost.className}`}>
      <body>
        <Header />
        <main className="pt-[98px] md:pt-[154px]">{children}</main>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
