import "./globals.css";
import { Jost, League_Spartan } from "next/font/google";

export const metadata = {
  title: "Designo",
  description: "Generated by create next app",
};

const jost = Jost({
  variable: "--font-jost",
  display: "swap",
});

const leagueSpartan = League_Spartan({
  variable: "--font-league-spartan",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jost.className} ${leagueSpartan.className}`}>
      <body>
        <header>Header</header>
        <main>{children}</main>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
