import Header from "@/components/Header";
import "./globals.css";
import { Jost } from "next/font/google";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Designo",
  description: "Generated by create next app",
};

const jost = Jost({
  variable: "--font-jost",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${jost.className}`}>
      <body className="bg-[size:1006px_594px] bg-[position:top_475px_left,_right_top_1880px] bg-no-repeat lg:bg-[url(../assets/shared/desktop/bg-pattern-leaf.svg),_url(../assets/exports/rectangle-right-aligned.svg)]">
        <Header />
        <main className="mb-[120px] grow pt-[98px] md:mb-[80px] md:px-10 md:pt-[154px] lg:mb-[160px]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
